### PR TITLE
Open ranger when vim load a directory

### PR DESCRIPTION
**Pull request by code-andres**
Now vim open ranger.vim when a directory is passed by argument.

### CODE REVIEW

**Comment by francoiscabrol** [comment]
it looks great! I just require one simple thing before merging this feature: please add an option to enable this feature (disabled by default). I don't want to change the current default behaviours since many people use this plugin and don't expect it to change. You can surround `ReplaceNetrwByRangerVim` by a condition like `if g:replace_netrw`. Then the user has just to add `let g:ranger_map_keys = ` in his .vimrc/.nvimrc. After the merge I will update the README myself don't worry about that.

**Comment by code-andres** [comment]
Yeah, i forget about that, sorry... Ok i will add that condition.

**Comment by code-andres** [comment]
For use ranger.vim along side with nerdtree and setting ranger as default file explorer, the nerdtree auto-load must be disabled with this option: `let g:NERDTreeHijackNetrw = 0`

**Comment by francoiscabrol** [comment]
awesome thank you!

**Comment by francoiscabrol** [comment]
@code-andres did you implement it for vim or neovim? I tried with neovim and I have an issue... no rush to fix it since it's an option and not yet defined in the doc.

**Comment by code-andres** [comment]
I use neovim and i don't have any problem.

**Comment by francoiscabrol** [comment]
It works! I just forgot to add the line `let g:NERDTreeHijackNetrw = 0` :)

**Comment by code-andres** [comment]
Yeah, don't forget that line, it cancel the auto-load for NERDTree. Without that line NERDTree and ranger.vim start at the same time.

**Comment by akarl818** [comment]
Would be nice with an update to the docs as well.

**Comment by francoiscabrol** [comment]
yes sorry I have to do it

**Comment by francoiscabrol** [comment]
readme updated!

**Pull request merged**
